---
title: "avgfieldsizecountry"
author: "Espi Garschina-Bobrow"
date: "2024-04-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Data and Insight
```{r, eval=FALSE}
library(dplyr)
library(sf)
library(terra)

data_dir <- here::here("external/afcdata")
data_dir

flds <- sfarrow::st_read_parquet(
  file.path(data_dir, "mapped_fields_final.parquet"))

ctlg <- readr::read_csv(
  file.path(data_dir, "label_catalog_allclasses.csv"))

names(ctlg)

length(unique(ctlg$assignment_id)) == nrow(ctlg)

length(unique(ctlg$name))

```

Spatial Characteristics
```{r, eval=FALSE}
polybox <- function(x, y, w = 0.0025, crs = 4326) {
dw <- cbind(c(x - w, x + w, x + w, x - w, x - w),
c(y + w, y + w, y - w, y - w, y + w))
st_sf(geometry = st_sfc(st_polygon(list(dw))), crs = crs)
}

set.seed(2)
site <- ctlg %>%
filter(nflds > 0) %>%
sample_n(1) %>%
select(name, assignment_id, nflds, farea, x, y) %>%
mutate(polybox(x, y)) %>%
st_as_sf()
p <- ggplot() +
geom_sf(data = site) +
theme_linedraw()
p

```

Calculating areas
```{r, eval=FALSE}

#long form

flds %>%
st_transform("ESRI:102022") %>%
mutate(area = as.numeric(st_area(.)) / 10000) %>%
st_transform(4326)

#fields totally inside the box could be selected using the x, y coordinates to find the nearest field

site_xy <- site %>%
st_drop_geometry() %>% # dropping the polygon we made first
st_as_sf(coords = c("x", "y"), crs = 4326) # make back into spatial point
nearest_fld <- site_flds %>% slice(st_nearest_feature(site_xy, .))
p2 +
geom_sf(data = nearest_fld, fill = "blue") +
geom_sf(data = site_xy, col = "orange")
```

By country

```{r, eval=FALSE}

ctlg %>%
mutate(cntry = substr(name, 1, 2)) %>% # get country prefix from name
group_by(cntry) %>%
count() %>% View()

```

Averages by country
```{r, eval=FALSE}

ctry_mean <- ctlg %>%
mutate(cntry = substr(name, 1, 2)) %>%
select(name, cntry, farea) %>%
group_by(cntry) %>%
summarize(farea = mean(farea, na.rm = TRUE))
left_join(ctry_mean, cntries, by = c("cntry" = "ISO2"))

```




