---
title: "exampleCode"
author: "Harrison Leduc"
date: "2024-04-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r, include = FALSE, echo = FALSE}
library(geospaar)
districts <- system.file("extdata/districts.geojson", package = "geospaar") %>%   st_read %>% mutate(ID = 1:nrow(.))

wctemp <- geodata::worldclim_country(var = "tavg", res = 2.5, 
                                     country = "Zambia", path = tempdir())

```



```{r}
zamtmean <- mask(app(wctemp, mean), districts)
trng <- global(zamtmean, range, na.rm = TRUE)
reclmat <- cbind(c(floor(trng[1]), 20, 24), c(20, 24, ceiling(trng[2])), 1:3)

zamtclass <- classify(x = zamtmean, rcl = unlist(reclmat), include.lowest = TRUE)

cols <- c("blue", "yellow2", "red")

plot_noaxes(zamtclass, legend = FALSE, main = "Average Temps", col = cols,
            mar = c(0, 0, 2, 2))
legend(x = "bottomright", inset = 0.168,
       col = cols, pch = 15, pt.cex = 2,
       legend = c('Low', 'Medium', 'High'))
```
