---
title: "uncertainty"
author: "Harrison Leduc"
date: "2024-04-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Data and Insight
```{r}
library(dplyr)
library(sf)
library(terra)

data_dir <- here::here("external/afcdata")

# temporary work around
#data_dir <- file.path("~/external/afcdata")

flds <- sfarrow::st_read_parquet(
  file.path(data_dir, "mapped_fields_final.parquet"))

ctlg <- readr::read_csv(
  file.path(data_dir, "label_catalog_allclasses.csv"))

#Data check
#names(ctlg)

#length(unique(ctlg$assignment_id)) == nrow(ctlg)

#length(unique(ctlg$name))

```

Spatial Features/Characteristics
```{r}
library(ggplot2)

polybox <- function(x, y, w = 0.0025, crs = 4326) {
  dw <- cbind(c(x - w, x + w, x + w, x - w, x - w),
              c(y + w, y + w, y - w, y - w, y + w))
  st_sf(geometry = st_sfc(st_polygon(list(dw))), crs = crs)
}

set.seed(2)
site <- ctlg %>% 
  filter(nflds > 0) %>% 
  sample_n(1) %>% 
  select(name, assignment_id, nflds, farea, x, y) %>% 
  mutate(polybox(x, y)) %>% 
  st_as_sf()

p <- ggplot() +
  geom_sf(data = site) +
  theme_linedraw()
p
```

Digitized Boundaries
```{r}
ctlg %>% 
  mutate(flds = ifelse(nflds > 0, 1, nflds)) %>% 
  group_by(Class) %>% 
  summarize(hasflds = sum(flds),
            noflds = length(flds[flds == 0]))

site_flds <- flds %>% 
  filter(assignment_id == site$assignment_id)
site_flds

site

p2 <- p +
  geom_sf(data = site_flds, fill = "transparent", color = "red", lwd = 0.5)
p2
```

Label Uncertainty
```{r}
# OLD CODE
# From pdf for 1 site
# sites_mapped_gt2 <- ctlg %>% 
#   group_by(Class, name) %>% 
#   count() %>% 
#   ungroup() %>% 
#   filter(n > 2)
# 
# set.seed(10)
# # Select the ninth site (you can adjust this as needed)
# multi_site <- sites_mapped_gt2 %>% slice(9)
# 
# # Clarification: assignments = 'assns'
# multi_site_assns <- ctlg %>% filter(name == multi_site$name)
# 
# target <- multi_site_assns %>% 
#   slice(1) %>% 
#   mutate(polybox(x, y)) %>% 
#   st_as_sf()
# 
# # rasterize at 224, 224 pixels
# r <- rast(ext(target), nrows = 224, ncols = 224, crs = "EPSG:4326")
# values(r) <- 0
# 
# multi_site_assnsr <- lapply(1:nrow(multi_site_assns), function(x) {
#   assn <- multi_site_assns[x, ]
#   if(assn$nflds > 0) {
#     assn_flds <- flds %>%
#       filter(assignment_id == assn$assignment_id)
#     r <- rasterize(assn_flds, r, background = 0)
#   } else {
#     r
#   }
#   return(r)
# }) %>% do.call(c, .)
# 
# plot(multi_site_assnsr)

# pfield <- app(multi_site_assnsr, sum) / nlyr(multi_site_assnsr)
# plot(pfield)
```


```{r}
############################################################
# NEW CODE
sites_mapped_gt2_test <- ctlg %>%
  group_by(Class, name) %>%
  count() %>%
  ungroup() %>%
  filter(n > 2)
sites_mapped_gt2_test

# t <- list() lapply produces a list so don't need to put results into an indexed list

#test just 10
#multi_site_list <- lapply(1:10, function(x) {

multi_site_list <- lapply(1:nrow(sites_mapped_gt2_test), function(x) {
  multi_site_test <- sites_mapped_gt2_test %>% slice(x)

# Filter the associations for the selected site
  multi_site_assns_test <- ctlg %>% filter(name == multi_site_test$name)

# Create an empty raster with the same extent as the target site
  target_test <- multi_site_assns_test %>%
    slice(1) %>%
    mutate(polybox(x, y)) %>%
    st_as_sf()

  # Rasterize at 224x224 pixels
  r_test <- rast(ext(target_test), nrows = 224, ncols = 224, crs = "EPSG:4326")
  values(r_test) <- 0

  # Process each association
  multi_site_assnsr_test <- lapply(1:nrow(multi_site_assns_test), function(x) {
    assn_test <- multi_site_assns_test[x, ]
    if (assn_test$nflds > 0) {
      assn_flds_test <- flds %>%
        filter(assignment_id == assn_test$assignment_id)
      r_test <- rasterize(assn_flds_test, r_test, background = 0)
    } else {
      r_test
    }
    return(r_test)
  }) %>% do.call(c, .)
})




######################################################################

```

```{r}
thresholds <- seq(0, 1, 0.2)
reclmat <- data.frame(
  lower = thresholds[-length(thresholds)],
  upper = thresholds[-1],
  index = 1:5,
  class = c("No field, high confidence", "No field, medium confidence", "Uncertain", "Field, medium confidence", "Field, high confidence")
)



#  pfield_test_list[[x]] <- app(multi_site_list[[x]], sum) / nlyr(multi_site_list[[x]])

# code above wouldn't work, workaround lapply below
  # create intermediate variables for each site to allow the ratio to work (had errors trying to do it all in one since app doesn't like lists)

pfield_test_list <- lapply(1:length(multi_site_list), function(x) {
  app_result <- app(multi_site_list[[x]], sum)
  nlyr_result <- nlyr(multi_site_list[[x]])
  app_result / nlyr_result
})

conf_class_list <- lapply(1:length(pfield_test_list), function(x) {
  classify(pfield_test_list[[x]], rcl = reclmat[, -4], include.lowest = TRUE)
})


lapply(1:length(conf_class_list), function(x) {
  levels(conf_class_list) <- reclmat[, 3:4]
})

#Test
#plot(conf_class_list[[900]], mar = c(0, 1, 0, 12))

```
#### STILL NEED TO LAPPLY FOR PORTION BELOW!!!
```{r, warning = FALSE}
conf_table_test <- lapply(1:length(conf_class_list), function(x) {
  freq(conf_class_list[[x]])
})
#conf_table <- freq(conf_class)
#conf_table
conf_table_test[[2]]

nofld_test <- lapply(1:length(pfield_test_list), function(x) {
  mask(1 - pfield_test_list[[x]], pfield_test_list[[x]] < 0.5, maskvalue = 0, updatevalue = 0)
})
#nofld <- mask(1 - pfield, pfield < 0.5, maskvalue = 0, updatevalue = 0)
nofld_test[[2]]

fld_test <- lapply(1:length(pfield_test_list), function(x) {
  mask(pfield_test_list[[x]], pfield_test_list[[x]] >= 0.5, maskvalue = 0, updatevalue = 0)
})
#fld <- mask(pfield, pfield >= 0.5, maskvalue = 0, updatevalue = 0)
fld_test[[2]]


#fld_nofld_conf_test <- lapply(1:length(fld_test), function(x) {
#  c(fld_test[[x]], nofld_test[[x]], fld_test[[x]] + nofld_test[[x]])
#})

fld_nofld_conf_test <- lapply(1:4, function(x) {
  c(fld_test[[x]], nofld_test[[x]], fld_test[[x]] + nofld_test[[x]])
})

#fld_nofld_conf <- c(fld, nofld, fld + nofld)
fld_nofld_conf_test[[2]]

lapply(1:length(fld_nofld_conf_test), function(x) {
  c("field agreement", "no field agreement", "overall agreement")
})
#names(fld_nofld_conf) <- c("field agreement", "no field agreement", "overall agreement")

plot(fld_nofld_conf[[2]], nr = 1)

global(fld_nofld_conf[[3]], mean) # shows the mean overall agreement!
#fld_nofld_conf[[3]], mean
```


Next Tasks:
# create a boxplot for analysis
```{r}

```