---
title: "AvgFieldSizeCountryTime"
author: "Moses Millman"
date: "2024-04-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data and Insight

```{r, message= FALSE} 
library(dplyr)
library(sf)
library(terra)


data_dir <- here::here("external/afcdata")

flds <- sfarrow::st_read_parquet(
     file.path(data_dir, "mapped_fields_final.parquet"))
   
ctlg <- readr::read_csv(
  file.path(data_dir, "label_catalog_allclasses.csv"))
```

# Spatial Characteristics

```{r, message= FALSE}
library(ggplot2)

length(unique(ctlg$assignment_id)) == nrow(ctlg)

polybox <- function(x, y, w = 0.0025, crs = 4326) {
     dw <- cbind(c(x - w, x + w, x + w, x - w, x - w),
                 c(y + w, y + w, y - w, y - w, y + w))
     st_sf(geometry = st_sfc(st_polygon(list(dw))), crs = crs)
 }
 
set.seed(2)
site <- ctlg %>%
     filter(nflds > 0) %>%
     sample_n(1) %>%
     select(name, assignment_id, nflds, farea, x, y) %>%
     mutate(polybox(x, y)) %>%
     st_as_sf()
```

# Averages by Country

```{r, message= FALSE}
#Load the packages
library(geodata)
library(maps)


#Averages by Country
site_flds <- flds %>% filter(assignment_id == site$assignment_id)

#Mutate cntry and year
ctlg <- ctlg %>%
     mutate(cntry = substr(name, 1, 2)) %>%  
     mutate(year = lubridate::year(image_date)) 

#Group by cntry and year and count
ctlg_grouped <- ctlg %>%
     group_by(cntry, year) %>%
     count() 

#Filter countries in Africa from the country codes data
cntries <- geodata::country_codes() %>%
     filter(continent == "Africa")

#Calculate average field area by country
ctry_mean <- ctlg %>%
  select(name, cntry, farea) %>%
  group_by(cntry) %>%
  summarize(farea = mean(farea, na.rm = TRUE))
```

# Averages by Country by Year

```{r, warning= FALSE, fig.width=10}
ctry_year_mean <- ctlg %>%
  mutate(cntry = substr(name, 1, 2),
         year = lubridate::year(image_date)) %>%
  group_by(cntry, year) %>%
  summarize(farea = mean(farea, na.rm = TRUE))

#Join with country codes
result <- left_join(ctry_year_mean, cntries, by = c("cntry" = "ISO2"))

#Plot
ggplot(result, aes(x = year, y = farea, group = NAME, color = NAME)) +
  geom_line() +
  labs(title = "Average Field Area Over Time by Country",
       x = "Year", y = "Average Field Area") +
  theme_minimal() +
  theme(legend.position = "bottom") +
  scale_fill_manual(values=c("#FFCC00", "#FF9900", "#FF6600", "#FF3300", "#CC9900", "#FFCC66", "#FF9966", "#FF6633", "#CC3300", "#CC0033", "#FF0033", "#FF3366", "#FF6699", "#FF66CC", "#990033", "#FF6666", "#CC6666", "#996666", "#663333", "#CC9999", "#CC6699", "#660033", "#660066", "#663366", "#CC99CC", "#996699", "#CC99FF", "#9966CC", "#663399", "#6600CC", "#660099", "#9933CC", "#330099", "#666699", "#333399", "#3333FF", "#003399", "#006699", "#000066"))
```

# Join with country codes

```{r, warning= FALSE, fig.width=10}
result_year <- left_join(ctry_year_mean, cntries, by = c("cntry" = "ISO2"))

ggplot(result_year, aes(x = year, y = farea, group = NAME, color = NAME)) +
  geom_line() +
  labs(title = "Average Field Area Over Time by Country",
       x = "Year", y = "Average Field Area") +
  theme_minimal() +
  theme(legend.position = "bottom") +
  scale_fill_manual(values=c("#FFCC00", "#FF9900", "#FF6600", "#FF3300", "#CC9900", "#FFCC66", "#FF9966", "#FF6633", "#CC3300", "#CC0033", "#FF0033", "#FF3366", "#FF6699", "#FF66CC", "#990033", "#FF6666", "#CC6666", "#996666", "#663333", "#CC9999", "#CC6699", "#660033", "#660066", "#663366", "#CC99CC", "#996699", "#CC99FF", "#9966CC", "#663399", "#6600CC", "#660099", "#9933CC", "#330099", "#666699", "#333399", "#3333FF", "#003399", "#006699", "#000066"))
```

# Grouping by country and year and calculating mean field area

```{r, message= FALSE}
ctry_year_mean <- ctlg %>%
  mutate(cntry = substr(name, 1, 2),
         year = lubridate::year(image_date)) %>%
  group_by(cntry, year) %>%
  summarize(farea = mean(farea, na.rm = TRUE))

#Joining with country code data
left_join(ctry_year_mean, cntries, by = c("cntry" = "ISO2"))
```
